# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /workspaces/Volume-Computation-Tests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /workspaces/Volume-Computation-Tests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Volume-Computation-Tests/CMakeFiles /workspaces/Volume-Computation-Tests/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /workspaces/Volume-Computation-Tests/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named volume_estimation_testing_vpoly

# Build rule for target.
volume_estimation_testing_vpoly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 volume_estimation_testing_vpoly
.PHONY : volume_estimation_testing_vpoly

# fast build rule for target.
volume_estimation_testing_vpoly/fast:
	$(MAKE) -f CMakeFiles/volume_estimation_testing_vpoly.dir/build.make CMakeFiles/volume_estimation_testing_vpoly.dir/build
.PHONY : volume_estimation_testing_vpoly/fast

#=============================================================================
# Target rules for targets named lp_solve

# Build rule for target.
lp_solve: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lp_solve
.PHONY : lp_solve

# fast build rule for target.
lp_solve/fast:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/build
.PHONY : lp_solve/fast

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.o: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.o

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.o

# target to build an object file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.o
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.o

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.i: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.i

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.i
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.i

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.s: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.s

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.s
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.c.s

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.o: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.o

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.o

# target to build an object file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.o
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.o

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.i: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.i

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.i
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.i

volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.s: volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.s

.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.s
.PHONY : volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.c.s

volesti/external/_deps/lpsolve-src/colamd/colamd.o: volesti/external/_deps/lpsolve-src/colamd/colamd.c.o

.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.o

# target to build an object file
volesti/external/_deps/lpsolve-src/colamd/colamd.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/colamd/colamd.c.o
.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.c.o

volesti/external/_deps/lpsolve-src/colamd/colamd.i: volesti/external/_deps/lpsolve-src/colamd/colamd.c.i

.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/colamd/colamd.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/colamd/colamd.c.i
.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.c.i

volesti/external/_deps/lpsolve-src/colamd/colamd.s: volesti/external/_deps/lpsolve-src/colamd/colamd.c.s

.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/colamd/colamd.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/colamd/colamd.c.s
.PHONY : volesti/external/_deps/lpsolve-src/colamd/colamd.c.s

volesti/external/_deps/lpsolve-src/ini.o: volesti/external/_deps/lpsolve-src/ini.c.o

.PHONY : volesti/external/_deps/lpsolve-src/ini.o

# target to build an object file
volesti/external/_deps/lpsolve-src/ini.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/ini.c.o
.PHONY : volesti/external/_deps/lpsolve-src/ini.c.o

volesti/external/_deps/lpsolve-src/ini.i: volesti/external/_deps/lpsolve-src/ini.c.i

.PHONY : volesti/external/_deps/lpsolve-src/ini.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/ini.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/ini.c.i
.PHONY : volesti/external/_deps/lpsolve-src/ini.c.i

volesti/external/_deps/lpsolve-src/ini.s: volesti/external/_deps/lpsolve-src/ini.c.s

.PHONY : volesti/external/_deps/lpsolve-src/ini.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/ini.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/ini.c.s
.PHONY : volesti/external/_deps/lpsolve-src/ini.c.s

volesti/external/_deps/lpsolve-src/lp_Hash.o: volesti/external/_deps/lpsolve-src/lp_Hash.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_Hash.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_Hash.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.c.o

volesti/external/_deps/lpsolve-src/lp_Hash.i: volesti/external/_deps/lpsolve-src/lp_Hash.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_Hash.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_Hash.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.c.i

volesti/external/_deps/lpsolve-src/lp_Hash.s: volesti/external/_deps/lpsolve-src/lp_Hash.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_Hash.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_Hash.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_Hash.c.s

volesti/external/_deps/lpsolve-src/lp_MDO.o: volesti/external/_deps/lpsolve-src/lp_MDO.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_MDO.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MDO.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.c.o

volesti/external/_deps/lpsolve-src/lp_MDO.i: volesti/external/_deps/lpsolve-src/lp_MDO.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_MDO.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MDO.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.c.i

volesti/external/_deps/lpsolve-src/lp_MDO.s: volesti/external/_deps/lpsolve-src/lp_MDO.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_MDO.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MDO.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_MDO.c.s

volesti/external/_deps/lpsolve-src/lp_MPS.o: volesti/external/_deps/lpsolve-src/lp_MPS.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_MPS.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MPS.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.c.o

volesti/external/_deps/lpsolve-src/lp_MPS.i: volesti/external/_deps/lpsolve-src/lp_MPS.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_MPS.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MPS.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.c.i

volesti/external/_deps/lpsolve-src/lp_MPS.s: volesti/external/_deps/lpsolve-src/lp_MPS.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_MPS.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_MPS.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_MPS.c.s

volesti/external/_deps/lpsolve-src/lp_SOS.o: volesti/external/_deps/lpsolve-src/lp_SOS.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_SOS.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_SOS.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.c.o

volesti/external/_deps/lpsolve-src/lp_SOS.i: volesti/external/_deps/lpsolve-src/lp_SOS.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_SOS.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_SOS.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.c.i

volesti/external/_deps/lpsolve-src/lp_SOS.s: volesti/external/_deps/lpsolve-src/lp_SOS.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_SOS.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_SOS.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_SOS.c.s

volesti/external/_deps/lpsolve-src/lp_crash.o: volesti/external/_deps/lpsolve-src/lp_crash.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_crash.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_crash.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.c.o

volesti/external/_deps/lpsolve-src/lp_crash.i: volesti/external/_deps/lpsolve-src/lp_crash.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_crash.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_crash.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.c.i

volesti/external/_deps/lpsolve-src/lp_crash.s: volesti/external/_deps/lpsolve-src/lp_crash.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_crash.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_crash.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_crash.c.s

volesti/external/_deps/lpsolve-src/lp_lib.o: volesti/external/_deps/lpsolve-src/lp_lib.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_lib.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_lib.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.c.o

volesti/external/_deps/lpsolve-src/lp_lib.i: volesti/external/_deps/lpsolve-src/lp_lib.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_lib.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_lib.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.c.i

volesti/external/_deps/lpsolve-src/lp_lib.s: volesti/external/_deps/lpsolve-src/lp_lib.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_lib.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_lib.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_lib.c.s

volesti/external/_deps/lpsolve-src/lp_matrix.o: volesti/external/_deps/lpsolve-src/lp_matrix.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_matrix.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_matrix.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.c.o

volesti/external/_deps/lpsolve-src/lp_matrix.i: volesti/external/_deps/lpsolve-src/lp_matrix.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_matrix.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_matrix.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.c.i

volesti/external/_deps/lpsolve-src/lp_matrix.s: volesti/external/_deps/lpsolve-src/lp_matrix.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_matrix.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_matrix.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_matrix.c.s

volesti/external/_deps/lpsolve-src/lp_mipbb.o: volesti/external/_deps/lpsolve-src/lp_mipbb.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_mipbb.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_mipbb.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.c.o

volesti/external/_deps/lpsolve-src/lp_mipbb.i: volesti/external/_deps/lpsolve-src/lp_mipbb.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_mipbb.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_mipbb.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.c.i

volesti/external/_deps/lpsolve-src/lp_mipbb.s: volesti/external/_deps/lpsolve-src/lp_mipbb.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_mipbb.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_mipbb.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_mipbb.c.s

volesti/external/_deps/lpsolve-src/lp_params.o: volesti/external/_deps/lpsolve-src/lp_params.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_params.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_params.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_params.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_params.c.o

volesti/external/_deps/lpsolve-src/lp_params.i: volesti/external/_deps/lpsolve-src/lp_params.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_params.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_params.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_params.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_params.c.i

volesti/external/_deps/lpsolve-src/lp_params.s: volesti/external/_deps/lpsolve-src/lp_params.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_params.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_params.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_params.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_params.c.s

volesti/external/_deps/lpsolve-src/lp_presolve.o: volesti/external/_deps/lpsolve-src/lp_presolve.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_presolve.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_presolve.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.c.o

volesti/external/_deps/lpsolve-src/lp_presolve.i: volesti/external/_deps/lpsolve-src/lp_presolve.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_presolve.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_presolve.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.c.i

volesti/external/_deps/lpsolve-src/lp_presolve.s: volesti/external/_deps/lpsolve-src/lp_presolve.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_presolve.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_presolve.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_presolve.c.s

volesti/external/_deps/lpsolve-src/lp_price.o: volesti/external/_deps/lpsolve-src/lp_price.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_price.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_price.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_price.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_price.c.o

volesti/external/_deps/lpsolve-src/lp_price.i: volesti/external/_deps/lpsolve-src/lp_price.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_price.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_price.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_price.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_price.c.i

volesti/external/_deps/lpsolve-src/lp_price.s: volesti/external/_deps/lpsolve-src/lp_price.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_price.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_price.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_price.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_price.c.s

volesti/external/_deps/lpsolve-src/lp_pricePSE.o: volesti/external/_deps/lpsolve-src/lp_pricePSE.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_pricePSE.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_pricePSE.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.c.o

volesti/external/_deps/lpsolve-src/lp_pricePSE.i: volesti/external/_deps/lpsolve-src/lp_pricePSE.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_pricePSE.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_pricePSE.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.c.i

volesti/external/_deps/lpsolve-src/lp_pricePSE.s: volesti/external/_deps/lpsolve-src/lp_pricePSE.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_pricePSE.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_pricePSE.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_pricePSE.c.s

volesti/external/_deps/lpsolve-src/lp_report.o: volesti/external/_deps/lpsolve-src/lp_report.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_report.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_report.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_report.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_report.c.o

volesti/external/_deps/lpsolve-src/lp_report.i: volesti/external/_deps/lpsolve-src/lp_report.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_report.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_report.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_report.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_report.c.i

volesti/external/_deps/lpsolve-src/lp_report.s: volesti/external/_deps/lpsolve-src/lp_report.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_report.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_report.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_report.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_report.c.s

volesti/external/_deps/lpsolve-src/lp_scale.o: volesti/external/_deps/lpsolve-src/lp_scale.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_scale.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_scale.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.c.o

volesti/external/_deps/lpsolve-src/lp_scale.i: volesti/external/_deps/lpsolve-src/lp_scale.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_scale.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_scale.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.c.i

volesti/external/_deps/lpsolve-src/lp_scale.s: volesti/external/_deps/lpsolve-src/lp_scale.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_scale.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_scale.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_scale.c.s

volesti/external/_deps/lpsolve-src/lp_simplex.o: volesti/external/_deps/lpsolve-src/lp_simplex.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_simplex.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_simplex.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.c.o

volesti/external/_deps/lpsolve-src/lp_simplex.i: volesti/external/_deps/lpsolve-src/lp_simplex.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_simplex.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_simplex.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.c.i

volesti/external/_deps/lpsolve-src/lp_simplex.s: volesti/external/_deps/lpsolve-src/lp_simplex.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_simplex.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_simplex.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_simplex.c.s

volesti/external/_deps/lpsolve-src/lp_utils.o: volesti/external/_deps/lpsolve-src/lp_utils.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_utils.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_utils.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.c.o

volesti/external/_deps/lpsolve-src/lp_utils.i: volesti/external/_deps/lpsolve-src/lp_utils.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_utils.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_utils.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.c.i

volesti/external/_deps/lpsolve-src/lp_utils.s: volesti/external/_deps/lpsolve-src/lp_utils.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_utils.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_utils.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_utils.c.s

volesti/external/_deps/lpsolve-src/lp_wlp.o: volesti/external/_deps/lpsolve-src/lp_wlp.c.o

.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.o

# target to build an object file
volesti/external/_deps/lpsolve-src/lp_wlp.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_wlp.c.o
.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.c.o

volesti/external/_deps/lpsolve-src/lp_wlp.i: volesti/external/_deps/lpsolve-src/lp_wlp.c.i

.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/lp_wlp.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_wlp.c.i
.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.c.i

volesti/external/_deps/lpsolve-src/lp_wlp.s: volesti/external/_deps/lpsolve-src/lp_wlp.c.s

.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/lp_wlp.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/lp_wlp.c.s
.PHONY : volesti/external/_deps/lpsolve-src/lp_wlp.c.s

volesti/external/_deps/lpsolve-src/shared/commonlib.o: volesti/external/_deps/lpsolve-src/shared/commonlib.c.o

.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.o

# target to build an object file
volesti/external/_deps/lpsolve-src/shared/commonlib.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/commonlib.c.o
.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.c.o

volesti/external/_deps/lpsolve-src/shared/commonlib.i: volesti/external/_deps/lpsolve-src/shared/commonlib.c.i

.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/shared/commonlib.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/commonlib.c.i
.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.c.i

volesti/external/_deps/lpsolve-src/shared/commonlib.s: volesti/external/_deps/lpsolve-src/shared/commonlib.c.s

.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/shared/commonlib.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/commonlib.c.s
.PHONY : volesti/external/_deps/lpsolve-src/shared/commonlib.c.s

volesti/external/_deps/lpsolve-src/shared/mmio.o: volesti/external/_deps/lpsolve-src/shared/mmio.c.o

.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.o

# target to build an object file
volesti/external/_deps/lpsolve-src/shared/mmio.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/mmio.c.o
.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.c.o

volesti/external/_deps/lpsolve-src/shared/mmio.i: volesti/external/_deps/lpsolve-src/shared/mmio.c.i

.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/shared/mmio.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/mmio.c.i
.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.c.i

volesti/external/_deps/lpsolve-src/shared/mmio.s: volesti/external/_deps/lpsolve-src/shared/mmio.c.s

.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/shared/mmio.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/mmio.c.s
.PHONY : volesti/external/_deps/lpsolve-src/shared/mmio.c.s

volesti/external/_deps/lpsolve-src/shared/myblas.o: volesti/external/_deps/lpsolve-src/shared/myblas.c.o

.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.o

# target to build an object file
volesti/external/_deps/lpsolve-src/shared/myblas.c.o:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/myblas.c.o
.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.c.o

volesti/external/_deps/lpsolve-src/shared/myblas.i: volesti/external/_deps/lpsolve-src/shared/myblas.c.i

.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.i

# target to preprocess a source file
volesti/external/_deps/lpsolve-src/shared/myblas.c.i:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/myblas.c.i
.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.c.i

volesti/external/_deps/lpsolve-src/shared/myblas.s: volesti/external/_deps/lpsolve-src/shared/myblas.c.s

.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.s

# target to generate assembly for a file
volesti/external/_deps/lpsolve-src/shared/myblas.c.s:
	$(MAKE) -f CMakeFiles/lp_solve.dir/build.make CMakeFiles/lp_solve.dir/volesti/external/_deps/lpsolve-src/shared/myblas.c.s
.PHONY : volesti/external/_deps/lpsolve-src/shared/myblas.c.s

volume_cg_vpolytope.o: volume_cg_vpolytope.cpp.o

.PHONY : volume_cg_vpolytope.o

# target to build an object file
volume_cg_vpolytope.cpp.o:
	$(MAKE) -f CMakeFiles/volume_estimation_testing_vpoly.dir/build.make CMakeFiles/volume_estimation_testing_vpoly.dir/volume_cg_vpolytope.cpp.o
.PHONY : volume_cg_vpolytope.cpp.o

volume_cg_vpolytope.i: volume_cg_vpolytope.cpp.i

.PHONY : volume_cg_vpolytope.i

# target to preprocess a source file
volume_cg_vpolytope.cpp.i:
	$(MAKE) -f CMakeFiles/volume_estimation_testing_vpoly.dir/build.make CMakeFiles/volume_estimation_testing_vpoly.dir/volume_cg_vpolytope.cpp.i
.PHONY : volume_cg_vpolytope.cpp.i

volume_cg_vpolytope.s: volume_cg_vpolytope.cpp.s

.PHONY : volume_cg_vpolytope.s

# target to generate assembly for a file
volume_cg_vpolytope.cpp.s:
	$(MAKE) -f CMakeFiles/volume_estimation_testing_vpoly.dir/build.make CMakeFiles/volume_estimation_testing_vpoly.dir/volume_cg_vpolytope.cpp.s
.PHONY : volume_cg_vpolytope.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... volume_estimation_testing_vpoly"
	@echo "... lp_solve"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.o"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.i"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/LUSOL/lusol.s"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.o"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.i"
	@echo "... volesti/external/_deps/lpsolve-src/bfp/bfp_LUSOL/lp_LUSOL.s"
	@echo "... volesti/external/_deps/lpsolve-src/colamd/colamd.o"
	@echo "... volesti/external/_deps/lpsolve-src/colamd/colamd.i"
	@echo "... volesti/external/_deps/lpsolve-src/colamd/colamd.s"
	@echo "... volesti/external/_deps/lpsolve-src/ini.o"
	@echo "... volesti/external/_deps/lpsolve-src/ini.i"
	@echo "... volesti/external/_deps/lpsolve-src/ini.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_Hash.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_Hash.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_Hash.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MDO.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MDO.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MDO.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MPS.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MPS.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_MPS.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_SOS.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_SOS.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_SOS.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_crash.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_crash.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_crash.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_lib.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_lib.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_lib.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_matrix.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_matrix.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_matrix.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_mipbb.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_mipbb.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_mipbb.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_params.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_params.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_params.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_presolve.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_presolve.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_presolve.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_price.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_price.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_price.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_pricePSE.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_pricePSE.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_pricePSE.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_report.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_report.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_report.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_scale.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_scale.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_scale.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_simplex.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_simplex.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_simplex.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_utils.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_utils.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_utils.s"
	@echo "... volesti/external/_deps/lpsolve-src/lp_wlp.o"
	@echo "... volesti/external/_deps/lpsolve-src/lp_wlp.i"
	@echo "... volesti/external/_deps/lpsolve-src/lp_wlp.s"
	@echo "... volesti/external/_deps/lpsolve-src/shared/commonlib.o"
	@echo "... volesti/external/_deps/lpsolve-src/shared/commonlib.i"
	@echo "... volesti/external/_deps/lpsolve-src/shared/commonlib.s"
	@echo "... volesti/external/_deps/lpsolve-src/shared/mmio.o"
	@echo "... volesti/external/_deps/lpsolve-src/shared/mmio.i"
	@echo "... volesti/external/_deps/lpsolve-src/shared/mmio.s"
	@echo "... volesti/external/_deps/lpsolve-src/shared/myblas.o"
	@echo "... volesti/external/_deps/lpsolve-src/shared/myblas.i"
	@echo "... volesti/external/_deps/lpsolve-src/shared/myblas.s"
	@echo "... volume_cg_vpolytope.o"
	@echo "... volume_cg_vpolytope.i"
	@echo "... volume_cg_vpolytope.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

